version: '3.8'

configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 2s
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['otel-collector:8889']
  otel_collector_config:
    content: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      processors:
        batch:
      exporters:
        prometheus:
          endpoint: "0.0.0.0:8889"
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus]

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    configs:
      - source: otel_collector_config
        target: /etc/otel-collector-config.yaml
        uid: '0'
        gid: '0'
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8889:8889"   # Prometheus metrics exposed here

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
        uid: '0'
        gid: '0'
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboard-definitions:/var/lib/grafana/dashboards/dashboard-definitions
    depends_on:
      - prometheus

  rabbitmq:
    container_name: "rabbitmq" 
    image: rabbitmq:3.8-management-alpine
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # RabbitMQ instance
      - '5672:5672'
      # Web Interface
      - '15672:15672'

  grpc-service:
    container_name: sum-grpc
    build:
      context: .
      dockerfile: Sum-gRPC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5122:8080"   # HTTP only
    depends_on:
      otel-collector:
        condition: service_started
      sqlserver:
        condition: service_started
         
  rest-service:
    container_name: sum-rest
    build:
      context: .
      dockerfile: Sum-REST/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5138:8080"   # HTTP only
    depends_on:
      - otel-collector
      - rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6-tests:/k6-tests
    working_dir: /k6-tests
    


volumes:
  prometheus-data:
  grafana-data:
  sqlserver-data:  